baseurl: http://example.org/
title: Hugo Website
theme: hugo-theme-nix
languageCode: en-us
disqusShortname: your_disqus_shortname
menu:
  header:
    - name: post
      url: post
      weight: 0
    - name: about
      url: about
      weight: 1
params:
  About: Hi I'm Hugo and this is my website. I am a developer, writer and family man.
    I like developing websites using Hugo, sports, nature, photography and travel.
    On this websites you can expect my projects and blog posts about everything I
    love. Enjoy!
  Email: your_email
  Favicon: /favicon.ico
  GithubID: your_github
  HeaderHostname: gohugo.io
  HeaderUsername: hugo
  LinkedInID: your_linkedin
  MediumID: your_medium
  Name: Mr Hugo
  ProfilePicture: /profile.jpg
  SoundcloudID: your_soundcloud
  SpotifyID: your_spotify
  TelegramID: your_telegram
  TwitterID: your_twitter
  YoutubeID: your_youtube
