baseurl: https://rpfreitas.xyz/
title: Rafael Pinto
theme: hugo-theme-nix
languageCode: en-us
# disqusShortname: your_disqus_shortname
menu:
  header:
    - name: post
      url: post
      weight: 0
    - name: about
      url: about
      weight: 1
params:
  About: Engenheiro de Produção formado pela UFRJ, testando novas habilidades. Ciência de dados, BI, análise financeira e esportes são de forte interesse. Divirta-se!
  Email: rpfreitas@rpfreitas.xyz
  Favicon: /logo_bgblack_6464.png
  GithubID: rpfreitasxyz
  HeaderHostname: arch
  HeaderUsername: rpfreitas
  LinkedInID: rafael-pinto-de-freitas
  CvURL: /CV_rpfreitas.pdf
  # MediumID: your_medium
  Name: Rafael Pinto
  ProfilePicture: /copia_rafa_quadrado_640x640.png
  # SoundcloudID: your_soundcloud
  SpotifyID: savqvtu9jbapz71nwvo7j3ynn
  # TelegramID: your_telegram
  # TwitterID: your_twitter
  # YoutubeID: your_youtube
